---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)

library(plotly)
```


```{r}
data("instacart")

instacart = 
  instacart %>%
  select(department, aisle, product_name, order_dow, order_hour_of_day, reordered)
```

Column {data-width=450}
-----------------------------------------------------------------------

### Chart A

```{r, warning=FALSE}
instacart %>%
  count(aisle, department, order_hour_of_day) %>%
  filter(
    n <= 100000
  ) %>%
  plot_ly(
    x = ~department, y = ~n, type = "scatter", mode = "markers", 
    color = ~order_hour_of_day, alpha = 0.5
  )
```

Column {data-width=550}
-----------------------------------------------------------------------

### Chart B

```{r, warning=FALSE}

instacart %>% 
  count(aisle) %>% 
  mutate(aisle = fct_reorder(aisle, n)) %>% 
  plot_ly(x = ~aisle, y = ~n, color = ~aisle, type = "bar", colors = "viridis")
```

### Chart C

```{r, warning=FALSE}
instacart %>%
  count(aisle, department, order_hour_of_day) %>%
  mutate(
    aisle = fct_reorder(aisle, order_hour_of_day)
  ) %>%
  filter(
    n <= 4000
  ) %>%
  plot_ly(y = ~n, color = ~department, type = "box", 
          colors = "viridis")
```

