---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

This page is about making some plotly examples.

```{r}
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

```{r}
data("instacart")

instacart = 
  instacart %>%
  select(department, aisle, product_name, order_dow, order_hour_of_day, reordered)
```

## Plotly bar chart

```{r}
instacart %>% 
  count(aisle) %>% 
  mutate(aisle = fct_reorder(aisle, n)) %>% 
  plot_ly(x = ~aisle, y = ~n, color = ~aisle, type = "bar", colors = "viridis")
```

## Plotly Scatterplot

```{r}
instacart %>%
  count(aisle, department, order_hour_of_day) %>%
  filter(
    n <= 100000
  ) %>%
  plot_ly(
    x = ~department, y = ~n, type = "scatter", mode = "markers", 
    color = ~order_hour_of_day, alpha = 0.5
  )
```

## Plotly Boxplot

```{r}
instacart %>%
  count(aisle, department, order_hour_of_day) %>%
  mutate(
    aisle = fct_reorder(aisle, order_hour_of_day)
  ) %>%
  filter(
    n <= 4000
  ) %>%
  plot_ly(y = ~n, color = ~department, type = "box", 
          colors = "viridis")
```


